-- Auto-generated item_basic rows for !grantbis curated gear.
-- Restores retail Rare/Ex flags from intake backup where available.
-- Apply: mysql -u root -p xidb < server/sql/z_imagine_xi_bis_gear_item_basic.sql
-- Also merged into server/sql/item_basic.sql for fresh imports.

SET NAMES utf8mb4;

SET @EQUIPMENT_TYPE = 6;
SET @WEAPON_TYPE = 7;
SET @FLAG_AUG_SENDABLE = 1;
SET @FLAG_GM_ONLY = 2;
SET @FLAG_MYSTERY_BOX = 4;
SET @FLAG_MOG_GARDEN = 8;
SET @FLAG_CAN_SEND_ACCT = 16;
SET @FLAG_INSCRIBABLE = 32;
SET @FLAG_NOAUCTION = 64;
SET @FLAG_SCROLL = 128;
SET @FLAG_LINKSHELL = 256;
SET @FLAG_CANUSE = 512;
SET @FLAG_CANTRADENPC = 1024;
SET @FLAG_CANEQUIP = 2048;
SET @FLAG_NOSALE = 4096;
SET @FLAG_NODELIVERY = 8192;
SET @FLAG_EX = 16384;
SET @FLAG_RARE = 32768;
SET @FLAG_NO_RECYCLE = 65536;
SET @FLAG_NO_RARE_CHECK = 131072;
SET @H2H = 1; SET @DAGGER = 2; SET @SWORD = 3; SET @GREATSWORD = 4; SET @AXE = 5;
SET @GREATAXE = 6; SET @SCYTHE = 7; SET @POLEARM = 8; SET @KATANA = 9; SET @GREATKATANA = 10;
SET @CLUB = 11; SET @STAFF = 12; SET @BOW = 13; SET @AMMUNITION = 15; SET @SHIELD = 16;
SET @HEAD = 17; SET @BODY = 18; SET @HANDS = 19; SET @LEGS = 20; SET @FEET = 21;
SET @NECK = 22; SET @WAIST = 23; SET @EARRINGS = 24; SET @RINGS = 25; SET @BACK = 26;

REPLACE INTO `item_basic` VALUES (11292,0,'mirage_jubbah','mirage_jubbah','mirage_jubbah',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (11298,0,'pantin_tobe','pantin_tobe','pantin_tobe',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (11307,0,'argute_gown','argute_gown','argute_gown',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (11308,0,'argute_gown_+1','argute_gown_+1','argute_gown_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (11382,0,'mirage_charuqs','mirage_charuqs','mirage_charuqs',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (11388,0,'pantin_babouches','pantin_babouches','pantin_babouches',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (11395,0,'sch._loafers_+1','sch._loafers_+1','sch._loafers_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (11399,0,'argute_loafers_+1','argute_loafers_+1','argute_loafers_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (11465,0,'mirage_keffiyeh','mirage_keffiyeh','mirage_keffiyeh',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (11471,0,'pantin_taj','pantin_taj','pantin_taj',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (11480,0,'argute_m.board','argute_m.board','argute_m.board',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (11481,0,'argute_m.board_+1','argute_m.board_+1','argute_m.board_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (11528,0,'besieger_mantle','besieger_mantle','besieger_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,0,0);
REPLACE INTO `item_basic` VALUES (11654,0,'puffin_ring','puffin_ring','puffin_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (11990,0,'healers_torque','healers_torque','healers_torque',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX,@NECK,0);
REPLACE INTO `item_basic` VALUES (12387,0,'koenig_shield','koenig_shield','koenig_shield',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (12409,0,'numinous_shield','numinous_shield','numinous_shield',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (12434,0,'genbus_kabuto','genbus_kabuto','genbus_kabuto',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12440,0,'leather_bandana','leather_bandana','leather_bandana',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12496,0,'copper_hairpin','copper_hairpin','copper_hairpin',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12513,0,'warlocks_chapeau','warlocks_chapeau','warlocks_chapeau',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12518,0,'hunters_beret','hunters_beret','hunters_beret',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12519,0,'drachen_armet','drachen_armet','drachen_armet',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12520,0,'evokers_horn','evokers_horn','evokers_horn',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12531,0,'silver_hairpin_+1','silver_hairpin_+1','silver_hairpin_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (12549,0,'koenig_cuirass','koenig_cuirass','koenig_cuirass',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12555,0,'haubergeon','haubergeon','haubergeon',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12562,0,'kirins_osode','kirins_osode','kirins_osode',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12576,0,'bronze_harness','bronze_harness','bronze_harness',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12577,0,'brass_harness','brass_harness','brass_harness',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12605,0,'nobles_tunic','nobles_tunic','nobles_tunic',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12609,0,'black_tunic','black_tunic','black_tunic',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12629,0,'lgn._harness','lgn._harness','lgn._harness',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (12640,0,'healers_bliaut','healers_bliaut','healers_bliaut',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12641,0,'wizards_coat','wizards_coat','wizards_coat',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12642,0,'warlocks_tabard','warlocks_tabard','warlocks_tabard',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12647,0,'choral_jstcorps','choral_jstcorps','choral_jstcorps',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12648,0,'hunters_jerkin','hunters_jerkin','hunters_jerkin',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12649,0,'drachen_mail','drachen_mail','drachen_mail',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12650,0,'evokers_doublet','evokers_doublet','evokers_doublet',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (12677,0,'kng._handschuhs','kng._handschuhs','kng._handschuhs',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12684,0,'thick_mufflers','thick_mufflers','thick_mufflers',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12696,0,'leather_gloves','leather_gloves','leather_gloves',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12701,0,'dusk_gloves','dusk_gloves','dusk_gloves',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12704,0,'bronze_mittens','bronze_mittens','bronze_mittens',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12749,0,'scentless_armlets','scentless_armlets','scentless_armlets',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (12805,0,'koenig_diechlings','koenig_diechlings','koenig_diechlings',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12818,0,'byakkos_haidate','byakkos_haidate','byakkos_haidate',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12824,0,'leather_trousers','leather_trousers','leather_trousers',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12832,0,'bronze_subligar','bronze_subligar','bronze_subligar',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12834,0,'bone_subligar','bone_subligar','bone_subligar',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12879,0,'dusk_trousers','dusk_trousers','dusk_trousers',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12881,0,'lgn._subligar','lgn._subligar','lgn._subligar',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (12933,0,'koenig_schuhs','koenig_schuhs','koenig_schuhs',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (12952,0,'leather_highboots','leather_highboots','leather_highboots',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (12957,0,'dusk_ledelsens','dusk_ledelsens','dusk_ledelsens',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (12960,0,'bronze_leggings','bronze_leggings','bronze_leggings',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (13052,0,'light_soleas','light_soleas','light_soleas',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (13071,0,'scale_gorget','scale_gorget','scale_gorget',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@NECK,0);
REPLACE INTO `item_basic` VALUES (13072,0,'bird_whistle','bird_whistle','bird_whistle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@NECK,0);
REPLACE INTO `item_basic` VALUES (13175,0,'ajari_necklace','ajari_necklace','ajari_necklace',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@NECK,0);
REPLACE INTO `item_basic` VALUES (13190,0,'heko_obi_+1','heko_obi_+1','heko_obi_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13192,0,'leather_belt','leather_belt','leather_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13194,0,'warriors_belt','warriors_belt','warriors_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13197,0,'koenigs_belt','koenigs_belt','koenigs_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13211,0,'friars_rope','friars_rope','friars_rope',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13231,0,'life_belt','life_belt','life_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (13282,0,'saintly_ring','saintly_ring','saintly_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BACK,0);
REPLACE INTO `item_basic` VALUES (13283,0,'saintly_ring_+1','saintly_ring_+1','saintly_ring_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BACK,0);
REPLACE INTO `item_basic` VALUES (13286,0,'soldiers_ring','soldiers_ring','soldiers_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (13289,0,'sorcerers_ring','sorcerers_ring','sorcerers_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (13312,0,'coral_earring','coral_earring','coral_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13375,0,'knowledge_earring','knowledge_earring','knowledge_earring',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13408,0,'triumph_earring','triumph_earring','triumph_earring',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13422,0,'sorcerers_earring','sorcerers_earring','sorcerers_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13437,0,'healers_earring','healers_earring','healers_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13439,0,'warlocks_earring','warlocks_earring','warlocks_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (13506,0,'bomb_ring','bomb_ring','bomb_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (13605,0,'cape_+1','cape_+1','cape_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,0,0);
REPLACE INTO `item_basic` VALUES (13607,0,'mist_silk_cape','mist_silk_cape','mist_silk_cape',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,0,0);
REPLACE INTO `item_basic` VALUES (13646,0,'amemet_mantle_+1','amemet_mantle_+1','amemet_mantle_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,0,0);
REPLACE INTO `item_basic` VALUES (13661,0,'healers_mantle','healers_mantle','healers_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,0,0);
REPLACE INTO `item_basic` VALUES (13662,0,'wizards_mantle','wizards_mantle','wizards_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,0,0);
REPLACE INTO `item_basic` VALUES (13663,0,'warlocks_mantle','warlocks_mantle','warlocks_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,0,0);
REPLACE INTO `item_basic` VALUES (13686,0,'jaguar_mantle','jaguar_mantle','jaguar_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,0,0);
REPLACE INTO `item_basic` VALUES (13690,0,'foragers_mantle','foragers_mantle','foragers_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,0,0);
REPLACE INTO `item_basic` VALUES (13729,0,'priests_robe','priests_robe','priests_robe',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (13818,0,'garrison_tunica','garrison_tunica','garrison_tunica',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (13855,0,'healers_cap','healers_cap','healers_cap',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (13856,0,'wizards_petasos','wizards_petasos','wizards_petasos',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (13857,0,'choral_roundlet','choral_roundlet','choral_roundlet',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (13915,0,'optical_hat','optical_hat','optical_hat',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (13952,0,'ochiudos_kote','ochiudos_kote','ochiudos_kote',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (13963,0,'healers_mitts','healers_mitts','healers_mitts',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (13970,0,'choral_cuffs','choral_cuffs','choral_cuffs',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (13974,0,'drachen_fng._gnt.','drachen_fng._gnt.','drachen_fng._gnt.',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (13975,0,'evokers_bracers','evokers_bracers','evokers_bracers',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14062,0,'carbuncle_mitts','carbuncle_mitts','carbuncle_mitts',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14067,0,'tarasque_mitts','tarasque_mitts','tarasque_mitts',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14091,0,'healers_duckbills','healers_duckbills','healers_duckbills',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (14102,0,'drachen_greaves','drachen_greaves','drachen_greaves',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (14103,0,'evokers_pigaches','evokers_pigaches','evokers_pigaches',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (14206,0,'garrison_boots','garrison_boots','garrison_boots',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (14227,0,'drachen_brais','drachen_brais','drachen_brais',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14228,0,'evokers_spats','evokers_spats','evokers_spats',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14303,0,'shura_haidate','shura_haidate','shura_haidate',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14314,0,'garrison_hose','garrison_hose','garrison_hose',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14317,0,'barone_cosciales','barone_cosciales','barone_cosciales',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14325,0,'seers_slacks','seers_slacks','seers_slacks',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14328,0,'seers_slacks_+1','seers_slacks_+1','seers_slacks_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (14404,0,'shm._hara-ate','shm._hara-ate','shm._hara-ate',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14424,0,'seers_tunic','seers_tunic','seers_tunic',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (14427,0,'seers_tunic_+1','seers_tunic_+1','seers_tunic_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BODY,0);
REPLACE INTO `item_basic` VALUES (14476,0,'wzd._coat_+1','wzd._coat_+1','wzd._coat_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14477,0,'wlk._tabard_+1','wlk._tabard_+1','wlk._tabard_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14482,0,'chl._jstcorps_+1','chl._jstcorps_+1','chl._jstcorps_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14502,0,'clr._bliaut_+1','clr._bliaut_+1','clr._bliaut_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14503,0,'src._coat_+1','src._coat_+1','src._coat_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14522,0,'corsairs_frac','corsairs_frac','corsairs_frac',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14546,0,'ares_cuirass','ares_cuirass','ares_cuirass',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14550,0,'skadis_cuirie','skadis_cuirie','skadis_cuirie',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14554,0,'usukane_haramaki','usukane_haramaki','usukane_haramaki',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14559,0,'anus_doublet','anus_doublet','anus_doublet',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14568,0,'askar_korazin','askar_korazin','askar_korazin',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14569,0,'denali_jacket','denali_jacket','denali_jacket',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14570,0,'goliard_saio','goliard_saio','goliard_saio',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14580,0,'scholars_gown','scholars_gown','scholars_gown',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (14625,0,'evokers_ring','evokers_ring','evokers_ring',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (14675,0,'woodsman_ring','woodsman_ring','woodsman_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@BACK,0);
REPLACE INTO `item_basic` VALUES (14739,0,'suppanomimi','suppanomimi','suppanomimi',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (14743,0,'bushinomimi','bushinomimi','bushinomimi',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (14792,0,'relaxing_earring','relaxing_earring','relaxing_earring',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (14803,0,'optical_earring','optical_earring','optical_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (14813,0,'brutal_earring','brutal_earring','brutal_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (14841,0,'garrison_gloves','garrison_gloves','garrison_gloves',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14856,0,'seers_mitts','seers_mitts','seers_mitts',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14859,0,'seers_mitts_+1','seers_mitts_+1','seers_mitts_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14876,0,'hachiman_kote','hachiman_kote','hachiman_kote',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14892,0,'hlr._mitts_+1','hlr._mitts_+1','hlr._mitts_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14893,0,'wzd._gloves_+1','wzd._gloves_+1','wzd._gloves_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14894,0,'wlk._gloves_+1','wlk._gloves_+1','wlk._gloves_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14899,0,'chl._cuffs_+1','chl._cuffs_+1','chl._cuffs_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14906,0,'nashira_gages','nashira_gages','nashira_gages',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14912,0,'src._gloves_+1','src._gloves_+1','src._gloves_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14929,0,'corsairs_gants','corsairs_gants','corsairs_gants',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14965,0,'skadis_bazubands','skadis_bazubands','skadis_bazubands',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14969,0,'usukane_gote','usukane_gote','usukane_gote',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14974,0,'anus_gages','anus_gages','anus_gages',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14983,0,'askar_manopolas','askar_manopolas','askar_manopolas',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (14985,0,'goliard_cuffs','goliard_cuffs','goliard_cuffs',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15025,0,'mirage_bazubands','mirage_bazubands','mirage_bazubands',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15031,0,'pantin_dastanas','pantin_dastanas','pantin_dastanas',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15037,0,'sch._bracers_+1','sch._bracers_+1','sch._bracers_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15041,0,'argute_bracers_+1','argute_bracers_+1','argute_bracers_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15066,0,'relic_shield','relic_shield','relic_shield',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (15075,0,'sorcerers_petas.','sorcerers_petas.','sorcerers_petas.',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15077,0,'assassins_bonnet','assassins_bonnet','assassins_bonnet',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15078,0,'valor_coronet','valor_coronet','valor_coronet',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15082,0,'scouts_beret','scouts_beret','scouts_beret',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15083,0,'saotome_kabuto','saotome_kabuto','saotome_kabuto',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15084,0,'koga_hatsuburi','koga_hatsuburi','koga_hatsuburi',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15089,0,'clerics_bliaut','clerics_bliaut','clerics_bliaut',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15090,0,'sorcerers_coat','sorcerers_coat','sorcerers_coat',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15092,0,'assassins_vest','assassins_vest','assassins_vest',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15093,0,'valor_surcoat','valor_surcoat','valor_surcoat',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15097,0,'scouts_jerkin','scouts_jerkin','scouts_jerkin',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15099,0,'koga_chainmail','koga_chainmail','koga_chainmail',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BODY,0);
REPLACE INTO `item_basic` VALUES (15104,0,'clerics_mitts','clerics_mitts','clerics_mitts',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15105,0,'sorcerers_gloves','sorcerers_gloves','sorcerers_gloves',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15107,0,'assassins_armlets','assassins_armlets','assassins_armlets',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15108,0,'valor_gauntlets','valor_gauntlets','valor_gauntlets',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15112,0,'scouts_bracers','scouts_bracers','scouts_bracers',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15114,0,'koga_tekko','koga_tekko','koga_tekko',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HANDS,0);
REPLACE INTO `item_basic` VALUES (15119,0,'clerics_pantaln.','clerics_pantaln.','clerics_pantaln.',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15120,0,'sorcerers_tonban','sorcerers_tonban','sorcerers_tonban',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15122,0,'assassins_culottes','assassins_culottes','assassins_culottes',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15123,0,'valor_breeches','valor_breeches','valor_breeches',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15127,0,'scouts_braccae','scouts_braccae','scouts_braccae',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15129,0,'koga_hakama','koga_hakama','koga_hakama',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15134,0,'clerics_duckbills','clerics_duckbills','clerics_duckbills',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15135,0,'sorcerers_sabots','sorcerers_sabots','sorcerers_sabots',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15137,0,'assassins_pouln.','assassins_pouln.','assassins_pouln.',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15138,0,'valor_leggings','valor_leggings','valor_leggings',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15142,0,'scouts_socks','scouts_socks','scouts_socks',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15144,0,'koga_kyahan','koga_kyahan','koga_kyahan',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15147,0,'garrison_sallet','garrison_sallet','garrison_sallet',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15163,0,'seers_crown','seers_crown','seers_crown',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15166,0,'seers_crown_+1','seers_crown_+1','seers_crown_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15185,0,'walkure_mask','walkure_mask','walkure_mask',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15227,0,'hlr._cap_+1','hlr._cap_+1','hlr._cap_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15228,0,'wzd._petasos_+1','wzd._petasos_+1','wzd._petasos_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15229,0,'wlk._chapeau_+1','wlk._chapeau_+1','wlk._chapeau_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15234,0,'chl._roundlet_+1','chl._roundlet_+1','chl._roundlet_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15241,0,'nashira_turban','nashira_turban','nashira_turban',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15248,0,'src._petasos_+1','src._petasos_+1','src._petasos_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15266,0,'corsairs_tricorne','corsairs_tricorne','corsairs_tricorne',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15270,0,'walahra_turban','walahra_turban','walahra_turban',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (15273,0,'mace_belt','mace_belt','mace_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15274,0,'staff_belt','staff_belt','staff_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15294,0,'warwolf_belt','warwolf_belt','warwolf_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15295,0,'hierarch_belt','hierarch_belt','hierarch_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15313,0,'seers_pumps','seers_pumps','seers_pumps',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (15316,0,'seers_pumps_+1','seers_pumps_+1','seers_pumps_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (15327,0,'fuma_sune-ate','fuma_sune-ate','fuma_sune-ate',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15330,0,'hmn._sune-ate','hmn._sune-ate','hmn._sune-ate',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@FEET,0);
REPLACE INTO `item_basic` VALUES (15355,0,'wzd._sabots_+1','wzd._sabots_+1','wzd._sabots_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15356,0,'wlk._boots_+1','wlk._boots_+1','wlk._boots_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15361,0,'chl._slippers_+1','chl._slippers_+1','chl._slippers_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15457,0,'swift_belt','swift_belt','swift_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15508,0,'justice_torque','justice_torque','justice_torque',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@NECK,0);
REPLACE INTO `item_basic` VALUES (15515,0,'peacock_amulet','peacock_amulet','peacock_amulet',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@NECK,0);
REPLACE INTO `item_basic` VALUES (15523,0,'chivalrous_chain','chivalrous_chain','chivalrous_chain',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@NECK,0);
REPLACE INTO `item_basic` VALUES (15543,0,'rajas_ring','rajas_ring','rajas_ring',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (15546,0,'fasting_ring','fasting_ring','fasting_ring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BACK,0);
REPLACE INTO `item_basic` VALUES (15564,0,'wzd._tonban_+1','wzd._tonban_+1','wzd._tonban_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15565,0,'wlk._tights_+1','wlk._tights_+1','wlk._tights_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15570,0,'chl._cannions_+1','chl._cannions_+1','chl._cannions_+1',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15577,0,'nashira_seraweels','nashira_seraweels','nashira_seraweels',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15583,0,'src._tonban_+1','src._tonban_+1','src._tonban_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15606,0,'yigit_seraweels','yigit_seraweels','yigit_seraweels',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15611,0,'sturdy_slacks','sturdy_slacks','sturdy_slacks',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANTRADENPC | @FLAG_CANEQUIP,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15629,0,'skadis_chausses','skadis_chausses','skadis_chausses',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15633,0,'usukane_hizayoroi','usukane_hizayoroi','usukane_hizayoroi',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15638,0,'anus_brais','anus_brais','anus_brais',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15649,0,'goliard_trews','goliard_trews','goliard_trews',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (15662,0,'nashira_crackows','nashira_crackows','nashira_crackows',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15668,0,'src._sabots_+1','src._sabots_+1','src._sabots_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15685,0,'corsairs_bottes','corsairs_bottes','corsairs_bottes',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15688,0,'amir_boots','amir_boots','amir_boots',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15715,0,'skadis_jambeaux','skadis_jambeaux','skadis_jambeaux',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15719,0,'usukane_sune-ate','usukane_sune-ate','usukane_sune-ate',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15724,0,'anus_gaiters','anus_gaiters','anus_gaiters',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15735,0,'goliard_clogs','goliard_clogs','goliard_clogs',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@FEET,0);
REPLACE INTO `item_basic` VALUES (15872,0,'clerics_belt','clerics_belt','clerics_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15884,0,'potent_belt','potent_belt','potent_belt',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15906,0,'mohbwa_sash_+1','mohbwa_sash_+1','mohbwa_sash_+1',@EQUIPMENT_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@WAIST,0);
REPLACE INTO `item_basic` VALUES (15979,0,'fowling_earring','fowling_earring','fowling_earring',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (15982,0,'priests_earring','priests_earring','priests_earring',@EQUIPMENT_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (16041,0,'federation_earring','federation_earring','federation_earring',@EQUIPMENT_TYPE,1,@FLAG_MOG_GARDEN | @FLAG_NOAUCTION | @FLAG_CANTRADENPC | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@EARRINGS,0);
REPLACE INTO `item_basic` VALUES (16084,0,'ares_mask','ares_mask','ares_mask',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16088,0,'skadis_visor','skadis_visor','skadis_visor',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16092,0,'usukane_somen','usukane_somen','usukane_somen',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16097,0,'anus_tiara','anus_tiara','anus_tiara',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16106,0,'askar_zucchetto','askar_zucchetto','askar_zucchetto',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16108,0,'goliard_chapeau','goliard_chapeau','goliard_chapeau',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16140,0,'scholars_m.board','scholars_m.board','scholars_m.board',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (16175,0,'muse_tariqah','muse_tariqah','muse_tariqah',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (16212,0,'cerberus_mantle','cerberus_mantle','cerberus_mantle',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,0,0);
REPLACE INTO `item_basic` VALUES (16275,0,'ancient_torque','ancient_torque','ancient_torque',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@NECK,0);
REPLACE INTO `item_basic` VALUES (16346,0,'mirage_shalwar','mirage_shalwar','mirage_shalwar',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (16352,0,'pantin_churidars','pantin_churidars','pantin_churidars',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (16363,0,'argute_pants_+1','argute_pants_+1','argute_pants_+1',@EQUIPMENT_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@LEGS,0);
REPLACE INTO `item_basic` VALUES (16396,0,'koenigs_knuckles','koenigs_knuckles','koenigs_knuckles',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@H2H,0);
REPLACE INTO `item_basic` VALUES (16450,0,'dagger','dagger','dagger',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@DAGGER,0);
REPLACE INTO `item_basic` VALUES (16535,0,'bronze_sword','bronze_sword','bronze_sword',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@SWORD,0);
REPLACE INTO `item_basic` VALUES (16583,0,'claymore','claymore','claymore',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@GREATSWORD,0);
REPLACE INTO `item_basic` VALUES (16602,0,'perdu_sword','perdu_sword','perdu_sword',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@GREATSWORD,0);
REPLACE INTO `item_basic` VALUES (16648,0,'legionnaires_axe','legionnaires_axe','legionnaires_axe',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@AXE,0);
REPLACE INTO `item_basic` VALUES (16707,0,'bhuj','bhuj','bhuj',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@GREATAXE,0);
REPLACE INTO `item_basic` VALUES (16753,0,'ceremonial_dagger','ceremonial_dagger','ceremonial_dagger',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@DAGGER,0);
REPLACE INTO `item_basic` VALUES (16768,0,'bronze_zaghnal','bronze_zaghnal','bronze_zaghnal',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@SCYTHE,0);
REPLACE INTO `item_basic` VALUES (16774,0,'scythe','scythe','scythe',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@SCYTHE,0);
REPLACE INTO `item_basic` VALUES (16833,0,'bronze_spear','bronze_spear','bronze_spear',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@POLEARM,0);
REPLACE INTO `item_basic` VALUES (16834,0,'brass_spear','brass_spear','brass_spear',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@POLEARM,0);
REPLACE INTO `item_basic` VALUES (16863,0,'cruel_spear','cruel_spear','cruel_spear',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@POLEARM,0);
REPLACE INTO `item_basic` VALUES (16919,0,'shinobi-gatana','shinobi-gatana','shinobi-gatana',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@KATANA,0);
REPLACE INTO `item_basic` VALUES (16920,0,'shinobi-gatana_+1','shinobi-gatana_+1','shinobi-gatana_+1',@WEAPON_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@KATANA,0);
REPLACE INTO `item_basic` VALUES (16960,0,'uchigatana','uchigatana','uchigatana',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (16966,0,'tachi','tachi','tachi',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (16982,0,'nodachi','nodachi','nodachi',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (17034,0,'bronze_mace','bronze_mace','bronze_mace',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17035,0,'mace','mace','mace',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17041,0,'holy_mace','holy_mace','holy_mace',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17089,0,'holly_staff','holly_staff','holly_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17103,0,'mercenarys_pole','mercenarys_pole','mercenarys_pole',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17108,0,'healing_staff','healing_staff','healing_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17130,0,'freeswords_staff','freeswords_staff','freeswords_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17133,0,'chanters_staff','chanters_staff','chanters_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17134,0,'dolphin_staff','dolphin_staff','dolphin_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17138,0,'willow_wand_+1','willow_wand_+1','willow_wand_+1',@WEAPON_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17140,0,'yew_wand_+1','yew_wand_+1','yew_wand_+1',@WEAPON_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17141,0,'solid_wand','solid_wand','solid_wand',@WEAPON_TYPE,1,@FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17161,0,'power_bow','power_bow','power_bow',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BOW,0);
REPLACE INTO `item_basic` VALUES (17217,0,'crossbow','crossbow','crossbow',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@BOW,0);
REPLACE INTO `item_basic` VALUES (17413,0,'hermits_wand','hermits_wand','hermits_wand',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17422,0,'blessed_hammer','blessed_hammer','blessed_hammer',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@CLUB,0);
REPLACE INTO `item_basic` VALUES (17509,0,'destroyers','destroyers','destroyers',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@H2H,0);
REPLACE INTO `item_basic` VALUES (17537,0,'windurstian_staff','windurstian_staff','windurstian_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17557,0,'light_staff','light_staff','light_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17559,0,'dark_staff','dark_staff','dark_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17567,0,'kirins_pole','kirins_pole','kirins_pole',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17577,0,'capricorn_staff','capricorn_staff','capricorn_staff',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (17741,0,'perdu_hanger','perdu_hanger','perdu_hanger',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SWORD,0);
REPLACE INTO `item_basic` VALUES (17771,0,'anju','anju','anju',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@KATANA,0);
REPLACE INTO `item_basic` VALUES (17772,0,'zushio','zushio','zushio',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@KATANA,0);
REPLACE INTO `item_basic` VALUES (17813,0,'soboro_sukehiro','soboro_sukehiro','soboro_sukehiro',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (17820,0,'gunromaru','gunromaru','gunromaru',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (17829,0,'hagun','hagun','hagun',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (17830,0,'wooden_katana','wooden_katana','wooden_katana',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@GREATKATANA,0);
REPLACE INTO `item_basic` VALUES (17858,0,'turbo_animator','turbo_animator','turbo_animator',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18023,0,'jambiya','jambiya','jambiya',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANEQUIP,@DAGGER,0);
REPLACE INTO `item_basic` VALUES (18117,0,'gimlet_spear','gimlet_spear','gimlet_spear',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANTRADENPC | @FLAG_CANEQUIP,@POLEARM,0);
REPLACE INTO `item_basic` VALUES (18139,0,'bomb_core','bomb_core','bomb_core',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@AMMUNITION,0);
REPLACE INTO `item_basic` VALUES (18211,0,'gawains_axe','gawains_axe','gawains_axe',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@GREATAXE,0);
REPLACE INTO `item_basic` VALUES (18221,0,'martial_bhuj','martial_bhuj','martial_bhuj',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@GREATAXE,0);
REPLACE INTO `item_basic` VALUES (18270,0,'mandau','mandau','mandau',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@DAGGER,0);
REPLACE INTO `item_basic` VALUES (18275,0,'caliburn','caliburn','caliburn',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SWORD,0);
REPLACE INTO `item_basic` VALUES (18276,0,'excalibur','excalibur','excalibur',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SWORD,0);
REPLACE INTO `item_basic` VALUES (18282,0,'ragnarok','ragnarok','ragnarok',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@GREATSWORD,0);
REPLACE INTO `item_basic` VALUES (18300,0,'gungnir','gungnir','gungnir',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@POLEARM,0);
REPLACE INTO `item_basic` VALUES (18306,0,'apocalypse','apocalypse','apocalypse',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SCYTHE,0);
REPLACE INTO `item_basic` VALUES (18312,0,'kikoku','kikoku','kikoku',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@KATANA,0);
REPLACE INTO `item_basic` VALUES (18336,0,'annihilator','annihilator','annihilator',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18344,0,'relic_bow','relic_bow','relic_bow',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18348,0,'yoichinoyumi','yoichinoyumi','yoichinoyumi',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18360,0,'faith_baghnakhs','faith_baghnakhs','faith_baghnakhs',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@H2H,0);
REPLACE INTO `item_basic` VALUES (18394,0,'pilgrims_wand','pilgrims_wand','pilgrims_wand',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@CLUB,0);
REPLACE INTO `item_basic` VALUES (18403,0,'high_mana_wand','high_mana_wand','high_mana_wand',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_INSCRIBABLE | @FLAG_CANTRADENPC | @FLAG_CANEQUIP,@CLUB,0);
REPLACE INTO `item_basic` VALUES (18425,0,'perdu_blade','perdu_blade','perdu_blade',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@KATANA,0);
REPLACE INTO `item_basic` VALUES (18491,0,'perdu_voulge','perdu_voulge','perdu_voulge',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@GREATAXE,0);
REPLACE INTO `item_basic` VALUES (18588,0,'perdu_staff','perdu_staff','perdu_staff',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (18599,0,'pestle','pestle','pestle',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (18702,0,'trump_gun','trump_gun','trump_gun',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18717,0,'perdu_bow','perdu_bow','perdu_bow',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18718,0,'perdu_crossbow','perdu_crossbow','perdu_crossbow',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (18841,0,'templar_mace','templar_mace','templar_mace',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@CLUB,0);
REPLACE INTO `item_basic` VALUES (18990,0,'tupsimati','tupsimati','tupsimati',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (18994,0,'laevateinn','laevateinn','laevateinn',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (18996,0,'vajra','vajra','vajra',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@DAGGER,0);
REPLACE INTO `item_basic` VALUES (18997,0,'burtgang','burtgang','burtgang',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SWORD,0);
REPLACE INTO `item_basic` VALUES (19005,0,'nirvana','nirvana','nirvana',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@STAFF,0);
REPLACE INTO `item_basic` VALUES (19023,0,'staff_strap','staff_strap','staff_strap',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (19025,0,'pole_grip','pole_grip','pole_grip',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (19037,0,'light_grip','light_grip','light_grip',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (19041,0,'rose_strap','rose_strap','rose_strap',@WEAPON_TYPE,1,@FLAG_CAN_SEND_ACCT | @FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@SHIELD,0);
REPLACE INTO `item_basic` VALUES (19202,0,'smart_grenade','smart_grenade','smart_grenade',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@AMMUNITION,0);
REPLACE INTO `item_basic` VALUES (19203,0,'war_hoop','war_hoop','war_hoop',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@BOW,0);
REPLACE INTO `item_basic` VALUES (19249,0,'thew_bomblet','thew_bomblet','thew_bomblet',@WEAPON_TYPE,1,@FLAG_MYSTERY_BOX | @FLAG_CANEQUIP | @FLAG_RARE,@AMMUNITION,0);
REPLACE INTO `item_basic` VALUES (21299,0,'yoichis_arrow','yoichis_arrow','yoichis_arrow',@WEAPON_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX,@AMMUNITION,0);
REPLACE INTO `item_basic` VALUES (27683,0,'acad._mortarboard','acad._mortarboard','acad._mortarboard',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (27786,0,'geomancy_galero','geomancy_galero','geomancy_galero',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
REPLACE INTO `item_basic` VALUES (27787,0,'runeist_bandeau','runeist_bandeau','runeist_bandeau',@EQUIPMENT_TYPE,1,@FLAG_NOAUCTION | @FLAG_CANEQUIP | @FLAG_NOSALE | @FLAG_NODELIVERY | @FLAG_EX | @FLAG_RARE,@HEAD,0);
